spring:
  application:
    name: runtime-service
  rabbitmq:
    host: localhost
    port: 5762
    stream:
      username: guest
      password: guest
eureka:
  client:
    service-url:
      defaul-zone: http://localhost:8761/eureka

api:
  base-url: http://localhost:8088
server:
  port: 8086