spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
  output:
    ansi:
      enabled: always
  security:
    jwt:
      secret-key: "${JWT_KEY}"
      expiration: 86400000 # 1ngay
      refresh-token:
        expiration: 604800000
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss}){blue} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
app:
  internal-secret: "${INTERNAL_SECRET}"